name: Check MidJourney Status

on:
  schedule:
    - cron: "30 21 * * *"  # Запуск в 01:00 UTC (через 1 час после 00:00)
    - cron: "30 23 * * *"  # Запуск в 03:00 UTC (через 3 часа после 00:00)

jobs:
  check-midjourney:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run fetch_media.py with zero-delay
        env:
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
          MIDJOURNEY_API_KEY: ${{ secrets.MIDJOURNEY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RUNWAY_API_KEY: ${{ secrets.RUNWAY_API_KEY }}
        run: |
          python scripts/fetch_media.py

      - name: Run b2_storage_manager.py
        env:
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
          MIDJOURNEY_API_KEY: ${{ secrets.MIDJOURNEY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RUNWAY_API_KEY: ${{ secrets.RUNWAY_API_KEY }}
        run: |
          python scripts/b2_storage_manager.py --zero-delay

