name: Run Main Script

on:
  workflow_dispatch:

jobs:
  run-b2-storage-manager:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print test message
      run: echo "Workflow успешно запущен"