name: Run Main Script

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск ежедневно в 00:00 UTC
  workflow_dispatch:  # Ручной запуск

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Debug PYTHONPATH
      run: echo "PYTHONPATH is set to: $PYTHONPATH"

    - name: Ensure required directories and files exist
      run: |
        # Проверка и создание директории data
        if [ ! -d core/data ]; then
          echo "Директория core/data отсутствует. Создаём её."
          mkdir -p core/data
        fi

        # Проверка и создание файла focus_tracker.json
        if [ ! -f core/data/focus_tracker.json ]; then
          echo "Файл focus_tracker.json отсутствует. Создаём его."
          echo "[]" > core/data/focus_tracker.json
        else
          echo "Файл focus_tracker.json найден."
        fi

        # Проверка и создание файла feedback_report.json
        if [ ! -f core/data/feedback_report.json ]; then
          echo "Файл feedback_report.json отсутствует. Создаём его."
          echo "{}" > core/data/feedback_report.json
        else
          echo "Файл feedback_report.json найден."
        fi

    - name: Run Main Script
      run: python scripts/main.py
      env:
        PYTHONPATH: ${{ github.workspace }}
