name: Test

on:
  schedule:
    - cron: '30 20 * * *'  # 20:30 UTC
  workflow_dispatch:

jobs:
  run-b2-storage-manager:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Извлечение кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка системных зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Очистка кэша pip
      run: |
        rm -rf ~/.cache/pip

    - name: Установка зависимостей Python
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt не найден"; exit 1; fi
        pip list  # Для диагностики

    - name: Установка переменных среды
      run: |
        echo "B2_ENDPOINT=${{ secrets.B2_ENDPOINT }}" >> $GITHUB_ENV
        echo "B2_ACCESS_KEY=${{ secrets.B2_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "B2_SECRET_KEY=${{ secrets.B2_SECRET_KEY }}" >> $GITHUB_ENV
        echo "B2_BUCKET_NAME=${{ secrets.B2_BUCKET_NAME }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "MIDJOURNEY_API_KEY=${{ secrets.MIDJOURNEY_API_KEY }}" >> $GITHUB_ENV
        echo "RUNWAY_API_KEY=${{ secrets.RUNWAY_API_KEY }}" >> $GITHUB_ENV

    - name: Проверка структуры директорий
      run: |
        ls -la
        ls -la scripts || echo "Каталог scripts не найден"

    # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
    - name: Запуск b2_storage_manager.py 
      run: |
          echo "--- GITHUB ACTION: Setting PYTHONPATH ---"
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/b2/b2
          echo "--- GITHUB ACTION: PYTHONPATH Set. Executing Python Script (Direct Output) ---"
          # Запускаем Python БЕЗ перенаправления в файл
          python -u scripts/b2_storage_manager.py --zero-delay || {
          echo "--- GITHUB ACTION: Python script failed! ---"
          exit 1 }
          echo "--- GITHUB ACTION: Python script finished (Direct Output). ---"
    

    - name: Загрузка логов как артефакта
      # Этот шаг теперь не найдет b2_storage_manager.log, так как мы его не создаем.
      # Его можно временно закомментировать или изменить 'path', чтобы он не вызывал ошибку,
      # но он не является причиной зависания. Оставим пока так.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: b2-storage-manager-logs
        path: b2_storage_manager.log # Файл не будет найден, но шаг с if: always() не прервет workflow
        retention-days: 7