name: B2 Storage Manager Workflow

on:
  schedule:
    - cron: '30 20 * * *'  # 20:30 UTC
  workflow_dispatch:

jobs:
  run-b2-storage-manager:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Извлечение кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка системных зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Установка зависимостей Python
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt не найден"; exit 1; fi
        pip list  # Покажем установленные пакеты для диагностики

    - name: Установка переменных среды
      run: |
        echo "B2_BUCKET_NAME=${{ secrets.B2_BUCKET_NAME }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "MIDJOURNEY_API_KEY=${{ secrets.MIDJOURNEY_API_KEY }}" >> $GITHUB_ENV
        echo "RUNWAY_API_KEY=${{ secrets.RUNWAY_API_KEY }}" >> $GITHUB_ENV

    - name: Проверка структуры директорий
      run: |
        ls -la
        ls -la scripts || echo "Каталог scripts не найден"

    - name: Тестовый запуск Python
      run: |
        python -c "import sys; print(sys.version); print(sys.path)" > test.log 2>&1

    - name: Запуск b2_storage_manager.py с диагностикой
      run: |
        python -u scripts/b2_storage_manager.py --zero-delay > b2_storage_manager.log 2>&1 || {
          echo "Ошибка выполнения b2_storage_manager.py, см. логи ниже:"
          cat b2_storage_manager.log
          exit 1
        }
        cat b2_storage_manager.log  # Покажем логи даже при успехе

    - name: Загрузка логов как артефакта
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: b2-storage-manager-logs
        path: |
          b2_storage_manager.log
          test.log
        retention-days: 7